
#define T_CHAR          1
#define T_INTEGER       2
#define T_VARS          3
#define T_PROGRAM       4
#define T_FUNCTION      5    
#define T_ENDFUNCTION   6
#define T_RETURN        7
#define T_STARTMAIN     8
#define T_ENDMAIN       9
#define T_WHILE         10
#define T_ENDWHILE      11
#define T_FOR           12
#define T_TO            13
#define T_STEP          14
#define T_ENDFOR        15
#define T_IF            16
#define T_THEN          17
#define T_ELSEIF        18
#define T_ELSE          19
#define T_ENDIF         20
#define T_END           21
#define T_OR            22
#define T_SWITCH        23
#define T_CASE          24
#define T_DEFAULT       25
#define T_ENDSWITCH     26
#define T_PRINT         27 
#define T_BREAK         28
#define T_STRUCT        29
#define T_ENDSTRUCT     30
#define T_OROP          31
#define T_ANDOP         32
#define T_EQUOP         33
#define T_ADDOP         34
#define T_MULOP         35
#define T_NOTOP         36
#define T_RELOP         37
#define T_LPAREN        38
#define T_RPAREN        39
#define T_SEMI          40
#define T_COMMA         41
#define T_ASSIGN        42
#define T_LBRACK        43
#define T_RBRACK        44
#define T_COMMENT       45
#define T_ICONST        46
#define T_CCONST        47
#define T_TYPEDEF       48
#define T_AND           49

